Fix running Docker Compose on most recent systems
Back in the days (TM) there used to be a separate docker-compose
command.

Then the Docker people added a docker compose subcommand[1].

As far as I understand the docker-compose command is not present in
the (most) recent Docker versions which made our build(s) fail[2]:

    Run docker-compose -f docker-compose-ci.yml run update_from_remote_schema
    /home/runner/work/_temp/ef6e0b15-9eec-483e-a40b-0c103f2759c1.sh: line 1: docker-compose: command not found
    Error: Process completed with exit code 127.

[1] https://github.com/docker-archive/compose-cli/issues/1404
[2] https://github.com/lune-climate/lune-ts/actions/runs/10354230801/job/28659010929