Fix "can't access property "errorCode"" (#1091)
In my earlier change I forgot that the way we were asserting the type
here was a bit dangerous.

error.response.data may or may not contain data.

Accessing one property on that is fine-ish (it will just evaluate to
undefined) but accessing a nested property is not (we'll try to access
a property on undefined).

This triggered a failure[1] _in error handling_ in the dashboard, which is
ironic:

    TypeError: can't access property "errorCode", o.error is undefined
    ../../../../node_modules/@lune-climate/lune/esm/core/ApiError.js:21 - dY1

Now we the assertion reflects reality much better and we can make this
code handle missing error information gracefully. The data is expected
to not be provided with some status codes, there's no issue there.

Fixes: 0157ac9506d6 ("Extract error details into ApiError (#1089)")

[1] https://app.bugsnag.com/lune/lune-dashboard/errors/696fab684b9fce566497939b?event_id=696fab6801628f9dd3f90000&i=sk&m=nw