Fix mass unit usage in the examples (#117)
Previously it would fail with

    test.ts:6:46 - error TS2339: Property 'Mass' does not exist on type 'typeof import("/lune-ts/example-usage/ts-usage/node_modules/@lune-climate/lune/esm/client")'.

    6         mass: { amount: '123.21', unit: lune.Mass.unit.T },
                                                   ~~~~

Mass is a type and it only exists at compile time.