Fix extracting errors from error responses, attempt 3
This error came up in production:

    TypeError: cannot use 'in' operator to search for "error" in "Unauthorized"

This is because I forgot earlier than error responses without defined
schema will just contain a text representation of the HTTP status.

This is a follow-up to [2] and [3], hopefully a final fix for this.

In this patch string replaced arbitrary objects because I think
non-error objects won't be present here and I shouldn've put string there
in the first place, not Record<never, never>.

[1] bc318c51bf62 ("Fix trying to access errorCode on undefined (#1097)")
[2] e33eed756423 ("Fix "can't access property "errorCode"" (#1091)")