Get rid of the chown hack by downgrading npm
Seems like chowning in GH Actions breaks the rebuild_schema_change
action which then fails[1] with:

  /usr/bin/git config --local --name-only --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader
  /usr/bin/git config --local --get-regexp http.https://github.com/.extraheader ^AUTHORIZATION:
  http.https://github.com/.extraheader AUTHORIZATION: basic ***
  /usr/bin/git config --local --unset http.https://github.com/.extraheader ^AUTHORIZATION:
  error: could not lock config file .git/config: Permission denied

It really looks like working directory permission issue so the chown is
a suspect – let's get rid of it and see.

[1] https://github.com/lune-climate/lune-ts/runs/6835801850?check_suite_focus=true