Manually fix code generation error
This change fixes the following error:

```
src/services/AccountsService.ts:277:23 - error TS2304: Cannot find name 'UploadLogoRequest'.

277             formData: UploadLogoRequest,
                          ~~~~~~~~~~~~~~~~~

src/services/ClientAccountsService.ts:250:23 - error TS2304: Cannot find name 'UploadLogoRequest'.

250             formData: UploadLogoRequest,
                          ~~~~~~~~~~~~~~~~~

Found 2 errors in 2 files.

Errors  Files
     1  src/services/AccountsService.ts:277
     1  src/services/ClientAccountsService.ts:250

```

Use `data` instead of` `UploadLogoRequest`.